name: Continous Builds2

on:
  push:
    branches: [qt6]

env:
  QT: 5.15.2

jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: install dep
        run: |
            sudo apt-get update
            sudo apt-get install libmariadb-dev cmake
      - name: install qt
        run: |
          pip install aqtinstall
          python3 -m aqt install-qt -O ${{ github.workspace }}/Qt/ linux desktop ${{env.QT}}
          echo ${{ github.workspace }}/Qt/${{env.QT}}/gcc_64/bin/ >> $GITHUB_PATH
      - name: build
        run: |
          ./build_qsql.sh ${{env.QT}} linux
          cd ${{ github.workspace }}/qtbase/src/plugins/sqldrivers/
          mkdir -p mariadb_driver/plugins/sqldrivers
          cp plugins/sqldrivers/libqsqlmysql.so mariadb_driver/plugins/sqldrivers
          cp /usr/lib/x86_64-linux-gnu/libmariadb.so mariadb_driver/

      - name: Linux artefact
        uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: ${{ github.workspace }}/qtbase/src/plugins/sqldrivers/mariadb_driver/
